# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: UCSD CSS 1
author: Ed Vul
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  allow_errors: true

parse:
  myst_substitutions:
    key: value
    url_website: "[Class Website](https://ucsd-css-002.github.io)"
    url_lecture: "[Lecture zoom (UCSD)](https://ucsd.zoom.us/j/93765261371)"
    url_lab: "[Lab zoom (UCSD)](https://ucsd.zoom.us/j/97219605542)"
    url_canvas: "[Canvas (UCSD)](https://canvas.ucsd.edu/courses/28075/)"
    url_campuswire: "[Campuswire](https://campuswire.com/c/G956AC5EB/feed)"
    url_deepnote: "[Deepnote](https://deepnote.com/dashboard/UCSD-CSS-1-summer-session-1/)"
    url_datahub: "[Datahub (UCSD)](https://datahub.ucsd.edu)"
    url_feedback: "[Feedback form (UCSD)](https://forms.gle/57Mfax3AQH5gM55A7)"

# Information about where the book exists on the web
repository:
  url: https://github.com/UCSD-CSS-001/ucsd-css-001.github.io  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
